### ISSUE TITLE
semmi

### ISSUE THREAD

**Issue by rolexend** [MicrosoftDocs/IntuneDocs.hu-hu#19]
[hello segített a tipp]

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: a98d7679-e19a-22b6-b8d2-2f98a66c9eac
* Version Independent ID: aba8bc26-ab00-c033-8fca-a878f9f87bbc
* Content: [A Windows Defender bekapcsolása](https://docs.microsoft.com/hu-hu/intune-user-help/turn-on-defender-windows#feedback)
* Content Source: [intune-user-help/turn-on-defender-windows.md](https://github.com/MicrosoftDocs/IntuneDocs.hu-hu/blob/live/intune-user-help/turn-on-defender-windows.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by srvbpigh** [comment]
Hello, @rolexend
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Üdvözöljük, @rolexend !

Köszönjük a megjegyzését. Igyekszünk javítani a docs.microsoft.com felhasználói élményét. Azonban további információra van szükségünk ahhoz, hogy visszajelzését feldolgozzuk. Kérjük, adjon meg további információkat, és pontosítsa a megjegyzéseit.

Üdvözlettel:
A Microsoft DOCS nemzetközi csapata

**Comment by CeciAc** [comment]
Üdvözöljük, @rolexend !
Még egyszer köszönjük megjegyzését.
Sajnos még mindig nem áll rendelkezésünkre elegendő információ ahhoz, hogy feldolgozzuk a visszajelzését. Ezt a GitHub-problémát most lezárjuk, de szívesen veszünk Öntől további visszajelzéseket a jövőben.
Üdvözlettel:
A Microsoft DOCS nemzetközi csapata
